### PR TITLE
[iot/btstack] add the final fixed config

### PR DESCRIPTION
**Pull request by supperthomas**

### CODE REVIEW

**Comment by supperthomas** [comment]
WB55软件包链接有些问题，已请相关人员修改。

**Comment by xupenghu** [comment]
Please review it again.

**Comment by armink** [comment]
ping @supperthomas

**Comment by supperthomas** [comment]
Ok  approve

**Review by supperthomas — COMMENTED** [review]
Approve

**Comment by supperthomas** [comment]
+1

**Pull request merged**
